@startuml

class Recette {
  id : INT <<PK>>
  titre : VARCHAR
  description : TEXT
  image_url : VARCHAR
  temps_preparation : INT
  temps_cuisson : INT
  portions : INT
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

class Ingredient {
  id : INT <<PK>>
  nom : VARCHAR <<UNIQUE>>
  image_url : VARCHAR
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

class Tag {
  id : INT <<PK>>
  nom : VARCHAR <<UNIQUE>>
  created_at : TIMESTAMP
  updated_at : TIMESTAMP
}

class RecetteIngredient {
  recette_id : INT <<PK, FK>>
  ingredient_id : INT <<PK, FK>>
  quantite : DECIMAL
  unite : VARCHAR
  notes : VARCHAR
}

class RecetteTag {
  recette_id : INT <<PK, FK>>
  tag_id : INT <<PK, FK>>
}

Recette "1" -- "0..*" RecetteIngredient
Ingredient "1" -- "0..*" RecetteIngredient

Recette "1" -- "0..*" RecetteTag
Tag "1" -- "0..*" RecetteTag

@enduml
